// utils/bannedDomains.js

const bannedDomains = [
    // Original domains
    "mailinator.com",
    "tempmail.com", 
    "disposablemail.com",
    
    // Popular temporary email services
    "10minutemail.com",
    "guerrillamail.com",
    "guerrillamail.net",
    "guerrillamail.org",
    "sharklasers.com",
    "yopmail.com",
    "yopmail.net",
    "yopmail.fr",
    "dispostable.com",
    "maildrop.cc",
    "harakirimail.com",
    "mailnesia.com",
    "mailinator.net",
    "mailinator2.com",
    "trashmail.com",
    "trashmail.net",
    "trashmail.me",
    "spamgourmet.com",
    "temp-mail.org",
    "temp-mail.ru",
    "tempmail.net",
    "throwawaymail.com",
    "getairmail.com",
    "getnada.com",
    
    // Additional disposable services
    "emailondeck.com",
    "eelmail.com",
    "trbvm.com",
    "drdrb.net",
    "dropmail.me",
    "mohmal.com",
    "fakeinbox.com",
    "armyspy.com",
    "cuvox.de",
    "dayrep.com",
    "einrot.com",
    "fleckens.hu",
    "gustr.com",
    "jourrapide.com",
    "rhyta.com",
    "teleworm.us",
    "superrito.com",
    "spambox.us",
    "jetable.org",
    "filzmail.com",
    "fakemail.net",
    "fakemailgenerator.com",
    "mintemail.com",
    "incognitomail.org",
    "discard.email",
    "tempr.email",
    "tempmail.ninja",
    "burnermail.io",
    "burnthis.email",
    
    // Less common but still used
    "spam4.me",
    "mailforspam.com",
    "killmail.net",
    "wegwerfemail.de",
    "trash-mail.de",
    "discard.one",
    "emailfake.com",
    "fakemailbox.com",
    "tempmailer.com",
    "mailcatch.com",
    "tempmailaddress.com",
    "tempinbox.com",
    "throwam.com",
    "pokemail.net",
    "mega.zik.dj"
  ];
  
  module.exports = bannedDomains;