export const pricingPlans = [
    {
      name: "Terra Novice",
      priceStart: "Rp70",
      priceStartSmall: ".000",
      priceEnd: "120",
      priceEndSmall: ".000",
      priceNote: "",
      features: [
        "Pengerjaan tugas ringan",
        "1 kali revisi",
        "Estimasi selesai 2-3 hari",
      ],
      buttonText: "Pesan Sekarang",
      popular: false,
    },
    {
      name: "Geo Force",
      priceStart: "Rp120",
      priceStartSmall: ".000",
      priceEnd: "450",
      priceEndSmall: ".000",
      priceNote: "(bisa nego)",
      features: [
        "Pengerjaan tugas menengah",
        "2 kali revisi",
        "Estimasi selesai 2-5 hari",
      ],
      buttonText: "Pesan Sekarang",
      popular: true,
    },
    {
      name: "Elemental Prime",
      priceStart: "Rp500",
      priceStartSmall: ".000",
      priceEnd: "750",
      priceEndSmall: ".000",
      priceNote: "(bisa nego)",
      features: [
        "Pengerjaan tugas kompleks (mini project)",
        "3 kali revisi",
        "Estimasi selesai 5-7 hari",
      ],
      buttonText: "Pesan Sekarang",
      popular: false,
    },
    {
      name: "Gaia Sovereign",
      priceStart: "Rp750",
      priceStartSmall: ".000",
      priceEnd: "3,5",
      priceEndSmall: " Juta",
      priceNote: "(bisa nego)",
      features: [
        "Pengerjaan project besar (web app/portfolio)",
        "Revisi bebas",
        "Estimasi selesai 1-2 minggu",
      ],
      buttonText: "Pesan Sekarang",
      popular: false,
    },
    {
        name: "Cosmic Elite",
        priceStart: "Rp150",
        priceStartSmall: ".000",
        priceEnd: "5",
        priceEndSmall: " Juta",
        priceNote: "harga disesuaikan dengan kesulitan project",
        features: [
          "Pengerjaan waktu mepet (web app/portfolio)",
          "Deadline Mepet 3 hari atau 2 hari",
          "Estimasi bisa selesai 1-2 hari atau kurang dari 12 jam",
        ],
        buttonText: "Pesan Sekarang",
        popular: false,
    }
  ];
  